development:
  adapter: postgresql
  encoding: unicode
  database: ticketing_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: ticketing_test
  pool: 5
  username: postgres
  password:
# 
# production:
#   adapter: postgresql
#   encoding: unicode
#   database: ticketing_production
#   pool: 5
#   username: postgres
#   password:
